### ISSUE TITLE
Client recommendations document features outdated branding

### ISSUE THREAD

**Issue by semioticrobotic** [redhat-cop/open-organization#1]
The client recommendation document features an outdated corporate logomark. See screenshot for context.

![Screenshot from 2019-08-08 10-47-54](https://user-images.githubusercontent.com/19554310/62713059-177b4e00-b9ca-11e9-8a12-4b0874154dd6.png)

**Comment by boogiespook** [comment]
Good spot - thanks very much.  I forgot to upload the most recent version.
![Screenshot from 2019-08-08 16-00-46](https://user-images.githubusercontent.com/3624001/62714132-e153c380-b9f5-11e9-98ee-409d385547c8.png)
