### ISSUE TITLE
Licensing terms seem ambiguous

### ISSUE THREAD

**Issue by semioticrobotic** [redhat-cop/open-organization#2]
The tool's [current license file](https://github.com/redhat-cop/open-organization/blob/master/LICENSE.md) specifies a Creative Commons license, which I've come to understand is not necessarily appropriate for application to software projects. To be sure, the license _does_ apply to the written content used in the tool, as that material comes from the Open Organization Maturity Model, which _is_ licensed via CC BY-SA 4.0.

Would a more robust licensing statement be more appropriate? Would specifying the license that governs the code, then distinguishing that from the license that governs the _prose_ be appropriate here?

**Comment by boogiespook** [comment]
I've added in an Apache 2 licenses to the code on github.  Agree that the content is Creative Commons and the code itself is Apache 2 (as used by the Open Practice Library)
