### ISSUE TITLE
Security cert is expired

### ISSUE THREAD

**Issue by LauraHilliger** [redhat-cop/open-organization#9]
https://www.ready-to-innovate.com/openorg/ <-- has an expired security certificate

**Comment by boogiespook** [comment]
Hi Laura,
Many thanks for the heads-up.  The certificate has now been renewed (it could take 5-10 mins to update on the site due to DNS caching).
Regards,
  Chris

**Comment by boogiespook** [comment]
https://www.sslshopper.com/ssl-checker.html#hostname=ready-to-innovate.com

**Comment by semioticrobotic** [comment]
Thanks, @boogiespook. (and thanks @LauraHilliger for catching it).
